/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-10 03:14:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/kje/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/kje/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668994839608L));
    _jspx_dependants.put("jar:file:/D:/kje/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/normalize.css\" />\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.1.4.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("body, html { font-family: 'Noto Sans KR', sans-serif; margin:0; padding:0;color: #333;\n");
      out.write("    line-height: 1.5;\n");
      out.write("    text-align: left;\n");
      out.write("    letter-spacing: -1px;}\n");
      out.write("\n");
      out.write("ul { list-style:none; }\n");
      out.write(".small-12 cell > label{font-size:25px;}\n");
      out.write("#logo { display:block; width:100px; height:50px; background-image:url(\"\"); background-color:white;\n");
      out.write("background-size:90% auto; background-repeat:no-repeat; background-position:center center;  z-index:91;}\n");
      out.write("\n");
      out.write(".h1 { padding-top:0.9rem; padding-bottom:0.3rem; }\n");
      out.write(".container { clear:both; width:100%; height:auto; margin:0 auto; }\n");
      out.write(".container::after { content:\"\"; display:block; width:100%; clear:both; }\n");
      out.write("\n");
      out.write("#header{font-size:18px;}\n");
      out.write("\n");
      out.write(".table{ border-spacing: 1px; border-color:#8f8f8f; text-align: center;margin-bottom: 5rem}\n");
      out.write(".tbody{border:1px solid #8f8f8f;}\n");
      out.write(".title { text-align: center;padding-top:36px; padding-bottom:70px; }\n");
      out.write(".agree_fr { width: 1000px; white-space:pre-wrap; margin: 10px auto; \n");
      out.write("padding: 24px; border:3px solid #eee; height:600px; overflow-y:auto; }\n");
      out.write(".form-check{margin-left:200px; padding-top:20px;}\n");
      out.write(".form-label{width:100px;}\n");
      out.write(".section{height:auto; min-height:100%; padding-bottom:181px; margin-bottom: 40px;}\n");
      out.write("\n");
      out.write("td a{color:#333;}\n");
      out.write(".nav-link dropdown-toggle {color:#333;}\n");
      out.write("\n");
      out.write(".btn-group, .btn-toolbar{float:right;}\n");
      out.write("\n");
      out.write(".mainVisual{position: relative; display:block; width:100%; height:70%; background-image:url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/main.png\"); background-color:white;\n");
      out.write("background-size:100% 90%; background-repeat:no-repeat; margin:0 auto; }\n");
      out.write("\n");
      out.write(".mainVisual .catch{\n");
      out.write("    position: absolute;\n");
      out.write("    top: 20vh;\n");
      out.write("    left: 55%;\n");
      out.write("    width: 100%;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    color: #fff;\n");
      out.write("    font-size: 50px;\n");
      out.write("    font-weight: 900;\n");
      out.write("    line-height: 1.35;\n");
      out.write("    -webkit-transform: translateX(-50%);\n");
      out.write("    -ms-transform: translateX(-50%);\n");
      out.write("    transform: translateX(-50%);\n");
      out.write("    text-shadow: 3px 3px 2px #555;\n");
      out.write("    letter-spacing: -0.03em;\n");
      out.write("}\n");
      out.write(".catch p {    font-family: \"Noto Sans KR\",sans-serif;\n");
      out.write("    text-align: left;\n");
      out.write("    color: #fff;\n");
      out.write("    font-size: 4vw;\n");
      out.write("    font-weight: 900;\n");
      out.write("    line-height: 1.35;\n");
      out.write("    text-shadow: 3px 3px 2px #555;\n");
      out.write("    letter-spacing: -0.03em;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;}\n");
      out.write("\n");
      out.write(".sub_visual {\n");
      out.write("    position: relative;\n");
      out.write("    height: 130px;\n");
      out.write("    background: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg_sub_visual.jpg\") no-repeat center center;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write(".lnb {\n");
      out.write("    position: relative;\n");
      out.write("    width: 188px;\n");
      out.write("    z-index: 9;\n");
      out.write("    padding: 80px 15px 30px;\n");
      out.write("    top: 70px;\n");
      out.write("    margin-left: 35px;\n");
      out.write("    border: solid 1px #eaeaea;\n");
      out.write("    border-top: 0px;\n");
      out.write("    float: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".lnb_tit_hidden {\n");
      out.write("    position: absolute;\n");
      out.write("    bottom: 0;\n");
      out.write("    left: 0;\n");
      out.write("    width: 188px;\n");
      out.write("    height: 60px;\n");
      out.write("    background-color: #4f8ec3;\n");
      out.write("    text-align: center;\n");
      out.write("    top: 0px;\n");
      out.write("    padding-top:1.5vh;\n");
      out.write("   \n");
      out.write("}\n");
      out.write(".sub_nav {\n");
      out.write("    color: #475055;\n");
      out.write("    font-size: 12px;\n");
      out.write("    font-weight: 400;\n");
      out.write("    margin-top: 6px;\n");
      out.write("    padding-top:15px;\n");
      out.write("}\n");
      out.write(".sub_nav a span {\n");
      out.write("    display: inline-block;\n");
      out.write("    font-size: 13px;\n");
      out.write("    color: #475055;\n");
      out.write("    padding: 0 5px;\n");
      out.write("}\n");
      out.write(".lnb li.lnb_dep1 {\n");
      out.write("    padding: 17px 0;\n");
      out.write("    border-bottom: solid 1px #dedede;\n");
      out.write("    text-align: left;\n");
      out.write("}\n");
      out.write(".lnb li.lnb_dep1 a {\n");
      out.write("	text-decoration:none;\n");
      out.write("    font-size: 15px;\n");
      out.write("    color: #475055;\n");
      out.write("    font-weight: 400;\n");
      out.write("}\n");
      out.write(".lnb li.lnb_dep1.on a {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write(".lnb li.lnb_dep2 {\n");
      out.write("    padding-top: 13px;\n");
      out.write("    text-indent: -10px;\n");
      out.write("    margin-left: 10px;\n");
      out.write("    border-bottom: solid 0px #dedede;\n");
      out.write("}\n");
      out.write(".lnb li.lnb_dep2 a {\n");
      out.write("	text-decoration:none;\n");
      out.write("    font-size: 13px;\n");
      out.write("    color: #76848b!important;\n");
      out.write("    padding-left: 10px;\n");
      out.write("}\n");
      out.write(".lnb li.lnb_dep2.on a {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sub_container {\n");
      out.write("    position: relative;\n");
      out.write("    width: 1000px;\n");
      out.write("    overflow: hidden;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    padding-bottom: 60px;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".sub_nav span {\n");
      out.write("    display: inline-block;\n");
      out.write("    font-size: 13px;\n");
      out.write("    color: #dedede;\n");
      out.write("    padding: 0 5px;\n");
      out.write("}\n");
      out.write(".visual_wrap .sub_nav {\n");
      out.write("    color: #fff;\n");
      out.write("    font-size: 12px;\n");
      out.write("    font-weight: 400;\n");
      out.write("    margin-top: 5px;\n");
      out.write("}\n");
      out.write(".content_area {\n");
      out.write("    position: relative;\n");
      out.write("    width: 100%;\n");
      out.write("    float: left;\n");
      out.write("    margin-left: 45px;\n");
      out.write("    overflow: hidden;\n");
      out.write("    line-height: normal;\n");
      out.write("    margin-top:2vh;\n");
      out.write("    \n");
      out.write("}\n");
      out.write(".content_body {\n");
      out.write("    position: relative;\n");
      out.write("    width: 1000px;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("}    \n");
      out.write(".message .message_txt01 {\n");
      out.write("    font-size: 30px;\n");
      out.write("    color: #373434;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    font-weight: 400;\n");
      out.write("    line-height: 1.2em;\n");
      out.write("    padding-top:50px;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".message {\n");
      out.write("    position: relative;\n");
      out.write("    background: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mini.png\") right no-repeat ;\n");
      out.write("    overflow: hidden;\n");
      out.write("    margin-bottom: 5em;\n");
      out.write("    font-size: 18px;\n");
      out.write("    line-height: 1.7em;\n");
      out.write("}\n");
      out.write("    \n");
      out.write(".row{padding-bottom: 70px;}\n");
      out.write(".col{width:33.3%; height:520px;}\n");
      out.write(".carousel-item img{width:100%; height:520px;}\n");
      out.write("\n");
      out.write(".bbs02_list {\n");
      out.write("    position: relative;\n");
      out.write("    overflow: hidden;\n");
      out.write("    width: 100%;\n");
      out.write("}\n");
      out.write(".bbs02_list ul li {\n");
      out.write("    float: left;\n");
      out.write("    margin: 0 21px 50px 0;\n");
      out.write("}\n");
      out.write(".bbs02_list .gallery_wrap {\n");
      out.write("    width: 281px;\n");
      out.write("    position: relative;\n");
      out.write("}\n");
      out.write(".bbs02_list .gallery_wrap a.gallery_img {\n");
      out.write("    width: 281px;\n");
      out.write("    height: 211px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bbs02_list .gallery_wrap a .icon_play {\n");
      out.write("    position: absolute;\n");
      out.write("    z-index: 999;\n");
      out.write("    top: 50%;\n");
      out.write("    left: 50%;\n");
      out.write("    width: 83px;\n");
      out.write("    height: 88px;\n");
      out.write("    margin: -80px 0 0 -35px;\n");
      out.write("    background: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/icon_play.png\") no-repeat;\n");
      out.write("}\n");
      out.write(".gallery_img img{width:280px;}\n");
      out.write(".gallery_wrap{    -webkit-text-size-adjust: 100%;\n");
      out.write("    color: #333;\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-weight: 400;\n");
      out.write("    font-family: \"Noto Sans KR\",sans-serif;\n");
      out.write("    letter-spacing: -1px;\n");
      out.write("    line-height: normal;\n");
      out.write("    list-style: none;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    width: 281px;\n");
      out.write("    position: relative;}\n");
      out.write("\n");
      out.write(".bbs02_list .gallery_wrap aside p {\n");
      out.write("    display: inline-block;\n");
      out.write("    font-size: 12px;\n");
      out.write("    color: #6d6d6d;\n");
      out.write("    padding: 5px 8px 5px 5px;\n");
      out.write("        text-decoration: none;\n");
      out.write("    color: #555;\n");
      out.write("    float:right;\n");
      out.write("}\n");
      out.write(".bbs02_list .gallery_wrap a.gallery_txt {\n");
      out.write("    font-size: 14px;\n");
      out.write("    color: #333;\n");
      out.write("    padding: 10px 0 10px 5px;\n");
      out.write("    display: block;\n");
      out.write("    height: 60px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("#footer{   box-sizing: border-box;\n");
      out.write("    display: block;\n");
      out.write("    border-top: 1px solid #ddd;\n");
      out.write("    background-color: #fff;\n");
      out.write("    width:100%;\n");
      out.write("    height:181px;\n");
      out.write("    font-size: 14px;\n");
      out.write("    position : relative;\n");
      out.write("  	bottom:0;\n");
      out.write("    background: #f1f1f1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write(".foot_bottom {    letter-spacing: -1px;\n");
      out.write("	display: block;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 50px;\n");
      out.write("    padding-left:120px;\n");
      out.write("    background: #f1f1f1;\n");
      out.write("    }\n");
      out.write(".foot_logo  {\n");
      out.write("    float: left;\n");
      out.write("    width: 140px;\n");
      out.write("    height:181px;\n");
      out.write("\n");
      out.write("}\n");
      out.write(".foot_bottom address {\n");
      out.write("    color: #555;\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-weight: 400;\n");
      out.write("}\n");
      out.write(".foot_bottom p {\n");
      out.write("    color: #777;\n");
      out.write("    margin-top: 5px;\n");
      out.write("}\n");
      out.write("</style>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/include/head.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path0");
      // /WEB-INF/views/include/head.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/head.jsp(6,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
