/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-09 00:36:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.data;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class intro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/kje/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/kje/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668994839608L));
    _jspx_dependants.put("jar:file:/D:/kje/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\r\n");
      out.write("<title>기관소개</title>\r\n");
      out.write("    <!-- 헤드 부분 인클루드 -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/head.jsp", out, false);
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../include/datatables.min.css\">\r\n");
      out.write("	<script src=\"../include/datatables.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <!-- 헤더 부분 인클루드 -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<section class=\"section\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"sub_visual visual01\">\r\n");
      out.write("		<!-- start lnb-->\r\n");
      out.write("			<div id=\"lnb_wrap\" class=\"lnb\">\r\n");
      out.write("				<div class=\"lnb_tit_hidden\">\r\n");
      out.write("					<h2 style=\"color:#fff;\">기관소개</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"lnb_dep1\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/icon_home.png\">\r\n");
      out.write("						<a href=\"/home/web/index.do?menuId=304\"><span>환경부</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"lnb_dep1 on\">\r\n");
      out.write("						<a href=\"/home/web/index.do?menuId=304\"><span>기관안내</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"lnb_dep1\">\r\n");
      out.write("						<a href=\"/home/web/index.do?menuId=307\"><span>알림</span></a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"lnb_dep2\"><a href=\"/home/web/index.do?menuId=307\">공지사항</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"lnb_dep1\">\r\n");
      out.write("						<a href=\"/home/web/index.do?menuId=307\"><span>국민소통</span></a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"lnb_dep2\"><a href=\"/home/web/index.do?menuId=307\">QNA</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"lnb_dep1\">\r\n");
      out.write("						<a href=\"/home/web/index.do?menuId=304\"><span>홍보</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"visual_wrap\">\r\n");
      out.write("              <h1 class=\"title\" style=\"color:#fff\"> 환경부 인사말 </h1>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("		<div class=\"sub_container\">\r\n");
      out.write("		<div class=\"content_area\">\r\n");
      out.write("			<div class=\"content_body\" id=\"content_body\">\r\n");
      out.write("	            <div class=\"message\" style=\"min-height:460px;\">\r\n");
      out.write("					<p class=\"message_txt01\">환경부 홈페이지를 방문해 주신 여러분, 반갑습니다.</p><br><br>\r\n");
      out.write("	\r\n");
      out.write("					<p class=\"message_txt02\">\r\n");
      out.write("					지금 우리는 전례 없는 이상기후와 <br/>\r\n");
      out.write("					다양하고 새로운 환경 이슈에 직면해 있습니다.<br/><br/>\r\n");
      out.write("					\r\n");
      out.write("					환경부는 '자율과 창의로 만드는 담대한 미래'란 국정 목표 아래<br/>\r\n");
      out.write("					'탄소중립 실현으로 지속 가능한 미래를 만들겠다'는 약속을  <br/>\r\n");
      out.write("					성실히 이행하겠습니다.<br/><br/>\r\n");
      out.write("					\r\n");
      out.write("					이를 위해 과학적인 탄소중립 이행과 녹색 경제 전환, <br/>\r\n");
      out.write("					기후 위기에 강한 물 환경과 자연 생태계 조성, <br/>\r\n");
      out.write("					미세먼지 걱정 없는 푸른 하늘, <br/>\r\n");
      out.write("					재활용을 통한 순환 경제 완성 등 <br/>\r\n");
      out.write("					주요 환경 과제들을 책임 있게 해결해 나가겠습니다. <br/><br/>\r\n");
      out.write("					\r\n");
      out.write("					과학기술과 혁신에 기반한 환경정책을 확립하고, <br/>\r\n");
      out.write("					소통과 협력으로 정책의 현장 적용성을 높이겠습니다. <br/><br/>\r\n");
      out.write("					\r\n");
      out.write("					국제 환경 질서에 능동적으로 대응하고, <br/>\r\n");
      out.write("					기존의 제도와 정책을 효율적으로 전환하겠습니다. <br/><br/>\r\n");
      out.write("					\r\n");
      out.write("					오로지 국민만을 바라보고<br/>\r\n");
      out.write("					박수받을 수 있는 환경부를 만들어 가겠습니다.<br/><br/>\r\n");
      out.write("					</p>\r\n");
      out.write("	\r\n");
      out.write("					<div class=\"sign\">\r\n");
      out.write("					    <img class=\"sign\" style=\"float:right; padding-right:100px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/ministor_sign.jpg\" alt=\"환경부 장관 환화진\" />\r\n");
      out.write("					</div>\r\n");
      out.write("			\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<footer id=\"footer\" class=\"footer-nav row expanded collapse\">\r\n");
      out.write("    <!-- 푸터 부분 인클루드 -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready( function () {\r\n");
      out.write("	    $('#tb1').DataTable();\r\n");
      out.write("	} );\r\n");
      out.write("	</script>		\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/data/intro.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/data/intro.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/data/intro.jsp(6,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
